// src/core/input/KeyCode.ts
// Canonical KeyboardEvent.code values (layout-independent).
// Based on W3C UI Events "code" table + common platform keys.
// Note: Not every browser emits every code, but the union is safe to use.

export const KeyCode = {
  // --- Letters ---
  KeyA: "KeyA",
  KeyB: "KeyB",
  KeyC: "KeyC",
  KeyD: "KeyD",
  KeyE: "KeyE",
  KeyF: "KeyF",
  KeyG: "KeyG",
  KeyH: "KeyH",
  KeyI: "KeyI",
  KeyJ: "KeyJ",
  KeyK: "KeyK",
  KeyL: "KeyL",
  KeyM: "KeyM",
  KeyN: "KeyN",
  KeyO: "KeyO",
  KeyP: "KeyP",
  KeyQ: "KeyQ",
  KeyR: "KeyR",
  KeyS: "KeyS",
  KeyT: "KeyT",
  KeyU: "KeyU",
  KeyV: "KeyV",
  KeyW: "KeyW",
  KeyX: "KeyX",
  KeyY: "KeyY",
  KeyZ: "KeyZ",

  // --- Digits (top row) ---
  Digit0: "Digit0",
  Digit1: "Digit1",
  Digit2: "Digit2",
  Digit3: "Digit3",
  Digit4: "Digit4",
  Digit5: "Digit5",
  Digit6: "Digit6",
  Digit7: "Digit7",
  Digit8: "Digit8",
  Digit9: "Digit9",

  // --- Function keys ---
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
  F11: "F11",
  F12: "F12",
  F13: "F13",
  F14: "F14",
  F15: "F15",
  F16: "F16",
  F17: "F17",
  F18: "F18",
  F19: "F19",
  F20: "F20",
  F21: "F21",
  F22: "F22",
  F23: "F23",
  F24: "F24",

  // --- Modifiers ---
  ShiftLeft: "ShiftLeft",
  ShiftRight: "ShiftRight",
  ControlLeft: "ControlLeft",
  ControlRight: "ControlRight",
  AltLeft: "AltLeft",
  AltRight: "AltRight",
  MetaLeft: "MetaLeft",
  MetaRight: "MetaRight",

  // --- Locks ---
  CapsLock: "CapsLock",
  NumLock: "NumLock",
  ScrollLock: "ScrollLock",

  // --- Whitespace & Entering ---
  Space: "Space",
  Tab: "Tab",
  Enter: "Enter",

  // --- Navigation ---
  ArrowUp: "ArrowUp",
  ArrowDown: "ArrowDown",
  ArrowLeft: "ArrowLeft",
  ArrowRight: "ArrowRight",
  Home: "Home",
  End: "End",
  PageUp: "PageUp",
  PageDown: "PageDown",

  // --- Editing ---
  Backspace: "Backspace",
  Delete: "Delete",
  Insert: "Insert",

  // --- UI / System ---
  Escape: "Escape",
  ContextMenu: "ContextMenu",
  PrintScreen: "PrintScreen",
  Pause: "Pause",

  // --- Punctuation / Symbols (US + Intl variants) ---
  Backquote: "Backquote",
  Minus: "Minus",
  Equal: "Equal",
  BracketLeft: "BracketLeft",
  BracketRight: "BracketRight",
  Backslash: "Backslash",
  Semicolon: "Semicolon",
  Quote: "Quote",
  Comma: "Comma",
  Period: "Period",
  Slash: "Slash",
  IntlBackslash: "IntlBackslash",
  IntlRo: "IntlRo",
  IntlYen: "IntlYen",

  // --- Numpad ---
  NumLockNumpad: "NumLock", // alias note: NumLock already above; some UAs emit same
  Numpad0: "Numpad0",
  Numpad1: "Numpad1",
  Numpad2: "Numpad2",
  Numpad3: "Numpad3",
  Numpad4: "Numpad4",
  Numpad5: "Numpad5",
  Numpad6: "Numpad6",
  Numpad7: "Numpad7",
  Numpad8: "Numpad8",
  Numpad9: "Numpad9",
  NumpadAdd: "NumpadAdd",
  NumpadSubtract: "NumpadSubtract",
  NumpadMultiply: "NumpadMultiply",
  NumpadDivide: "NumpadDivide",
  NumpadDecimal: "NumpadDecimal",
  NumpadEnter: "NumpadEnter",
  NumpadEqual: "NumpadEqual",
  NumpadComma: "NumpadComma",

  // --- IME / Language ---
  Convert: "Convert",
  NonConvert: "NonConvert",
  KanaMode: "KanaMode",
  KanjiMode: "KanjiMode",
  HangulMode: "HangulMode",
  Hanja: "Hanja",
  Lang1: "Lang1",
  Lang2: "Lang2",
  Lang3: "Lang3",
  Lang4: "Lang4",
  Lang5: "Lang5",
  // Compose & Dead keys (rare as code, common as key)
  Compose: "Compose",
  Dead: "Dead",

  // --- Media / Volume ---
  AudioVolumeMute: "AudioVolumeMute",
  AudioVolumeDown: "AudioVolumeDown",
  AudioVolumeUp: "AudioVolumeUp",
  MediaTrackNext: "MediaTrackNext",
  MediaTrackPrevious: "MediaTrackPrevious",
  MediaPlayPause: "MediaPlayPause",
  MediaStop: "MediaStop",

  // --- Launch / Application ---
  LaunchMail: "LaunchMail",
  LaunchApp1: "LaunchApp1",
  LaunchApp2: "LaunchApp2",

  // --- Power / System keys ---
  Power: "Power",
  Sleep: "Sleep",
  WakeUp: "WakeUp",
  Eject: "Eject",

  // --- Brightness ---
  BrightnessDown: "BrightnessDown",
  BrightnessUp: "BrightnessUp",

  // --- Browser keys (platform-dependent) ---
  BrowserBack: "BrowserBack",
  BrowserForward: "BrowserForward",
  BrowserRefresh: "BrowserRefresh",
  BrowserStop: "BrowserStop",
  BrowserSearch: "BrowserSearch",
  BrowserFavorites: "BrowserFavorites",
  BrowserHome: "BrowserHome",

  // --- Fn row (some laptops) ---
  Fn: "Fn",
  FnLock: "FnLock",
} as const

export type KeyCode = (typeof KeyCode)[keyof typeof KeyCode]

// Fast membership check + narrowing guard
const _set = new Set<KeyCode>(Object.values(KeyCode))
export function isKeyCode(code: string): code is KeyCode {
  return _set.has(code as KeyCode)
}

// Handy category buckets (optional; remove if you want a slimmer file)
export const KeyGroups = {
  Letters: [
    KeyCode.KeyA,
    KeyCode.KeyB,
    KeyCode.KeyC,
    KeyCode.KeyD,
    KeyCode.KeyE,
    KeyCode.KeyF,
    KeyCode.KeyG,
    KeyCode.KeyH,
    KeyCode.KeyI,
    KeyCode.KeyJ,
    KeyCode.KeyK,
    KeyCode.KeyL,
    KeyCode.KeyM,
    KeyCode.KeyN,
    KeyCode.KeyO,
    KeyCode.KeyP,
    KeyCode.KeyQ,
    KeyCode.KeyR,
    KeyCode.KeyS,
    KeyCode.KeyT,
    KeyCode.KeyU,
    KeyCode.KeyV,
    KeyCode.KeyW,
    KeyCode.KeyX,
    KeyCode.KeyY,
    KeyCode.KeyZ,
  ],
  Digits: [
    KeyCode.Digit0,
    KeyCode.Digit1,
    KeyCode.Digit2,
    KeyCode.Digit3,
    KeyCode.Digit4,
    KeyCode.Digit5,
    KeyCode.Digit6,
    KeyCode.Digit7,
    KeyCode.Digit8,
    KeyCode.Digit9,
  ],
  Arrows: [KeyCode.ArrowUp, KeyCode.ArrowDown, KeyCode.ArrowLeft, KeyCode.ArrowRight],
  Modifiers: [
    KeyCode.ShiftLeft,
    KeyCode.ShiftRight,
    KeyCode.ControlLeft,
    KeyCode.ControlRight,
    KeyCode.AltLeft,
    KeyCode.AltRight,
    KeyCode.MetaLeft,
    KeyCode.MetaRight,
  ],
  Navigation: [KeyCode.Home, KeyCode.End, KeyCode.PageUp, KeyCode.PageDown],
  Editing: [KeyCode.Backspace, KeyCode.Delete, KeyCode.Insert],
  Whitespace: [KeyCode.Space, KeyCode.Tab, KeyCode.Enter],
  Punctuation: [
    KeyCode.Backquote,
    KeyCode.Minus,
    KeyCode.Equal,
    KeyCode.BracketLeft,
    KeyCode.BracketRight,
    KeyCode.Backslash,
    KeyCode.Semicolon,
    KeyCode.Quote,
    KeyCode.Comma,
    KeyCode.Period,
    KeyCode.Slash,
    KeyCode.IntlBackslash,
    KeyCode.IntlRo,
    KeyCode.IntlYen,
  ],
  Function: [
    KeyCode.F1,
    KeyCode.F2,
    KeyCode.F3,
    KeyCode.F4,
    KeyCode.F5,
    KeyCode.F6,
    KeyCode.F7,
    KeyCode.F8,
    KeyCode.F9,
    KeyCode.F10,
    KeyCode.F11,
    KeyCode.F12,
    KeyCode.F13,
    KeyCode.F14,
    KeyCode.F15,
    KeyCode.F16,
    KeyCode.F17,
    KeyCode.F18,
    KeyCode.F19,
    KeyCode.F20,
    KeyCode.F21,
    KeyCode.F22,
    KeyCode.F23,
    KeyCode.F24,
  ],
  Numpad: [
    KeyCode.Numpad0,
    KeyCode.Numpad1,
    KeyCode.Numpad2,
    KeyCode.Numpad3,
    KeyCode.Numpad4,
    KeyCode.Numpad5,
    KeyCode.Numpad6,
    KeyCode.Numpad7,
    KeyCode.Numpad8,
    KeyCode.Numpad9,
    KeyCode.NumpadAdd,
    KeyCode.NumpadSubtract,
    KeyCode.NumpadMultiply,
    KeyCode.NumpadDivide,
    KeyCode.NumpadDecimal,
    KeyCode.NumpadEnter,
    KeyCode.NumpadEqual,
    KeyCode.NumpadComma,
  ],
  UI: [
    KeyCode.Escape,
    KeyCode.ContextMenu,
    KeyCode.PrintScreen,
    KeyCode.Pause,
    KeyCode.ScrollLock,
    KeyCode.CapsLock,
    KeyCode.NumLock,
  ],
  IME: [
    KeyCode.Convert,
    KeyCode.NonConvert,
    KeyCode.KanaMode,
    KeyCode.KanjiMode,
    KeyCode.HangulMode,
    KeyCode.Hanja,
    KeyCode.Lang1,
    KeyCode.Lang2,
    KeyCode.Lang3,
    KeyCode.Lang4,
    KeyCode.Lang5,
    KeyCode.Compose,
    KeyCode.Dead,
  ],
  Media: [
    KeyCode.AudioVolumeMute,
    KeyCode.AudioVolumeDown,
    KeyCode.AudioVolumeUp,
    KeyCode.MediaTrackNext,
    KeyCode.MediaTrackPrevious,
    KeyCode.MediaPlayPause,
    KeyCode.MediaStop,
  ],
  Launch: [KeyCode.LaunchMail, KeyCode.LaunchApp1, KeyCode.LaunchApp2],
  Power: [
    KeyCode.Power,
    KeyCode.Sleep,
    KeyCode.WakeUp,
    KeyCode.Eject,
    KeyCode.BrightnessDown,
    KeyCode.BrightnessUp,
  ],
  Browser: [
    KeyCode.BrowserBack,
    KeyCode.BrowserForward,
    KeyCode.BrowserRefresh,
    KeyCode.BrowserStop,
    KeyCode.BrowserSearch,
    KeyCode.BrowserFavorites,
    KeyCode.BrowserHome,
  ],
  Fn: [KeyCode.Fn, KeyCode.FnLock],
} as const
